-- APPROACH 1

SELECT D1.DEPT_NAME,E1.EMP_ID,E1.SALARY FROM DEPARTMENT AS D1
LEFT JOIN EMPLOYEE AS E1
ON D1.DEPT_ID=E1.DEPT_ID
AND E1.SALARY=(

SELECT MAX(E3.SALARY) FROM EMPLOYEE AS E3
WHERE E3.DEPT_ID=E1.DEPT_ID
AND E3.SALARY<
(
SELECT MAX(E2.SALARY) FROM EMPLOYEE AS E2
WHERE E2.DEPT_ID=E1.DEPT_ID

)
)






--APPROACH 2 



SELECT D1.DEPT_NAME,E1.EMP_ID,E1.SALARY 
FROM DEPARTMENT AS D1
LEFT JOIN EMPLOYEE AS E1
ON D1.DEPT_ID=E1.DEPT_ID
WHERE
(
SELECT COUNT(DISTINCT E2.SALARY) FROM EMPLOYEE AS E2
WHERE E2.DEPT_ID=E1.DEPT_ID
AND E2.SALARY>E1.SALARY
)